/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.vibestudio.app;

public final class R {
    public static final class attr {
    }
    public static final class bool {
        public static final int ms_rtlEnabled=0x7f040000;
    }
    public static final class drawable {
        public static final int bg_btn_primary=0x7f020000;
        public static final int bg_btn_secondary=0x7f020001;
        public static final int bg_card=0x7f020002;
        public static final int bg_step_circle_active=0x7f020003;
        public static final int bg_step_circle_inactive=0x7f020004;
    }
    public static final class id {
        public static final int btn_back=0x7f07000d;
        public static final int btn_menu=0x7f070001;
        public static final int btn_next=0x7f07000e;
        public static final int content_frame=0x7f070003;
        public static final int drawer_layout=0x7f070000;
        public static final int item_icon=0x7f07000f;
        public static final int item_title=0x7f070010;
        public static final int left_drawer=0x7f070005;
        public static final int left_drawer_container=0x7f070004;
        public static final int step1_indicator=0x7f070006;
        public static final int step1_layout=0x7f07000b;
        public static final int step1_title=0x7f070007;
        public static final int step2_indicator=0x7f070009;
        public static final int step2_layout=0x7f07000c;
        public static final int step2_title=0x7f07000a;
        public static final int step_divider=0x7f070008;
        public static final int toolbar_title=0x7f070002;
    }
    public static final class integer {
        public static final int ms_default_error_tab_animation_duration=0x7f050000;
        public static final int ms_warning_end_translate_y=0x7f050001;
    }
    public static final class layout {
        public static final int activity_main=0x7f030000;
        public static final int activity_onboarding=0x7f030001;
        public static final int drawer_list_item=0x7f030002;
    }
    public static final class string {
        public static final int ms_back=0x7f060002;
        public static final int ms_circle_path=0x7f060000;
        public static final int ms_complete=0x7f060004;
        public static final int ms_next=0x7f060003;
        public static final int ms_warning_path=0x7f060001;
    }
}
